---
- hosts: localhost
  gather_facts: true
  vars_files:
    - ./deployvariables.yml
  tasks:
  # LINUX VM
  - name: Clone a virtual machine from CentOS template and customize
    when: vmtype == "linux"
    register: vm
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ myvmdcname }}"
      cluster: "{{ myvmclname }}"
      name: "{{ vmhostname }}"
      annotation: "{{ vmdescription }}"
      folder: "/{{ myvmdcname }}/vm"
      template: "{{ template }}"
      networks:
      - name: "{{ vmnetworkname }}"
        ip: 192.168.101.99
        netmask: 255.255.255.0
        gateway: 192.168.101.2
      customization:
        dns_servers:
        - 192.168.101.104
        dns_suffix:
        - "{{ myaddomain }}"
        domain: "{{ myaddomain }}"
        timezone: "{{ mytimezone }}"
        hwclockUTC: true
      state: poweredon
      wait_for_ip_address: true
      wait_for_customization: true
  - debug: var=vm

  - name: Add newly created VM to inventory
    when: 
      - vm.instance is defined
      - vmtype == "linux"
    add_host:
      name: "{{ vm.instance.ipv4 }}"
      group: linuxvms
      hw_guest_id: "{{ vm.instance.hw_guest_id }}"
      hw_name: "{{ vm.instance.hw_name }}"

# LINUX VM      
- hosts: linuxvms
  gather_facts: true
  become: yes
  user: admbvtech
  vars_files:
    - ./deployvariables.yml
  tasks:
    - name: install security updates (CentOS8)
      register: security
      when: hw_guest_id == "centos8_64Guest"
      dnf:
        state: latest
        update_cache: yes
        security: yes
        name: '*'
    - name: install bugfix/errata (CentOS8)
      register: bugfix
      when: hw_guest_id == "centos8_64Guest"
      dnf:
        state: latest
        update_cache: yes
        bugfix: yes
        name: '*'
    - name: install security updates (CentOS7)
      register: security
      when: hw_guest_id == "centos7_64Guest"
      yum:
        state: latest
        update_cache: yes
        security: yes
        name: '*'
    - name: install bugfix/errata (CentOS7)
      register: bugfix
      when: hw_guest_id == "centos7_64Guest"
      yum:
        state: latest
        update_cache: yes
        bugfix: yes
        name: '*'
    - debug: var=security
    - debug: var=bugfix


  