---
- hosts: k8
  become: yes
  user: admbvtech
  gather_facts: true
  vars:
    k8s_cni: calico                                      # calico, flannel
    container_runtime: docker                            # docker, cri-o, containerd 
    configure_firewalld: true                            # true / false
    # Docker proxy support
    setup_proxy: false                                   # Set to true to configure proxy
    proxy_server: "proxy.example.com:8080"               # Proxy server address and port
    docker_proxy_exclude: "localhost,127.0.0.1"          # Adresses to exclude from proxy
  roles:
    - kubernetes-bootstrap
  tasks:
    - name: reboot vms
      reboot:
    - name: systemctl reload
      systemd:
        daemon_reload: yes
    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted
    - name: gather Docker images
      command:
        cmd: kubeadm config images pull

- hosts: master
  become: yes
  user: admbvtech
  gather_facts: true
  vars:
    k8folder: "k8s"
  vars_files:
    - ../deployvariables.yml
  tasks:
    - name: copy vSphere K8 configuration
      template:
        src: etc/kubernetes/vsphere.conf.j2
        dest: /etc/kubernetes/vsphere.conf
    - name: copy K8 init configuration
      template:
        src: etc/kubernetes/initdefault.yml.j2
        dest: /etc/kubernetes/initmaster.yml