# linea di comando:
# ansible-playbook -i external-inventory -i fsimonetti.vmware.yml --vault-password-file ~/.password --extra-vars @testvm11.yml deploy.yml
---
- hosts: localhost
  gather_facts: true
  vars_files:
    - ./acilia.yml
  tasks:
  # LINUX VM
  - name: complete deployment of a Linux VM
    when: vmtype == "linux" 
    block:
      - name: Clone a virtual machine from CentOS template and customize
        register: vm
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          datacenter: "{{ vsphere_datacenter }}"
          cluster: "{{ vsphere_cluster }}"
          datastore: "{{ vmdatastore }}"
          name: "{{ vmhostname }}"
          annotation: "{{ vmdescription }}"
          folder: "/{{ vsphere_datacenter }}/vm{{ vmfolder }}"
          template: "{{ template }}"
          hardware:
            memory_mb: "{{ vmram }}"
            num_cpus: "{{ vmcpu }}"
            osid: "{{ vmosid }}"
          disk:
          - size_gb: "{{ vmdisksize }}"
            type: "{{ vmdisktype }}"
            datastore: "{{ vmdatastore }}"
          networks:
          - name: "{{ vmnetname }}"
            ip: "{{ vmaddress }}"
            netmask: "{{ vmnetmask }}"
            gateway: "{{ vmgateway }}"
          customization:
            dns_servers:
            - "{{ addns1 }}"
            - "{{ addns2 }}"
            dns_suffix:
            - "{{ addomain }}"
            domain: "{{ addomain }}"
            timezone: "{{ adtimezone }}"
            hwclockUTC: true
          state: poweredon
          wait_for_ip_address: true
          wait_for_customization: true
      - name: Add newly created Linux VM to inventory
        add_host:
          name: "{{ vm.instance.ipv4 }}"
          group: linuxvms
          hw_guest_id: "{{ vm.instance.hw_guest_id }}"
          hw_guest_full_name: "{{ vm.instance.hw_guest_full_name }}"
          hw_name: "{{ vm.instance.hw_name }}"
      - name: record VM creation date/time
        shell: date +%Y%m%d%H%M
        register: deploydate
      - name: add attribute DEPLOYDATE to new VM
        vmware_guest_custom_attributes:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          name: "{{ vm.instance.hw_name }}"
          state: present
          attributes:
            - name: DEPLOYDATE
              value: "{{ deploydate.stdout }}"
      - name: add attribute DEPLOYTEMPLATE to new VM
        vmware_guest_custom_attributes:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          name: "{{ vm.instance.hw_name }}"
          state: present
          attributes:
            - name: DEPLOYTEMPLATE
              value: "{{ template }}"

# LINUX VM      
- hosts: linuxvms
  gather_facts: false
  become: yes
  user: admbvtech
  vars_files:
    - ./acilia.yml
  tasks:
  - name: get facts
    register: result
    setup:
  - name: print facts
    debug: var=result  