- name: set up Windows 2016 template
  hosts: all
  gather_facts: no
  tasks:
  - name: Adding local admin user
    win_user:
      name: admbvtech
      password: "{{ rootpass }}"
      state: present
      description: "local admin user"
      password_never_expires: yes
      user_cannot_change_password: yes
      groups:
        - Administrators
        - Users


  



    
