#!/bin/bash
echo -n "Enter VSPHEREPASSWORD: "
read VSPHEREPASSWORD
export VSPHEREPASSWORD
echo -n "Enter WINADMINPASSWORD: "
read WINADMINPASSWORD
export WINADMINPASSWORD
echo -n "Enter TEMPLATENETWORK: "
read TEMPLATENETWORKNAME
export TEMPLATENETWORKNAME
packer build main7.json
